version: '3.9'

services:
  web:
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: django01_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ..:/app
      - static_volume:/app/mysite/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: django01_nginx
    ports:
      - "8000:80"
    volumes:
      - static_volume:/app/mysite/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: django01_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  postgres_data:

